In [6]:
import torch as t
import numpy as np

In [7]:
torch.__version__

'1.10.0+cu111'

In [22]:
torch.cuda.is_available()

True

In [23]:
torch.cuda.current_device()

0

In [24]:
torch.cuda.get_device_name(0)

'Tesla K80'

In [8]:
lst =[1,2,3,4,5]
arr = np.array(lst)
arr.dtype

dtype('int64')

Convert Numpy to Tensor

In [9]:
tensor = t.from_numpy(arr)
tensor

tensor([1, 2, 3, 4, 5])

In [10]:
tensor.dtype

torch.int64

In [12]:
tensor[1:3]

tensor([2, 3])

In [15]:
## Disadvantage of from_numpy : The array and tensor takes same memory location
tensor[2] = 30
print(tensor)
print(arr)

tensor([ 1,  2, 30,  4,  5])
[ 1  2 30  4  5]


In [16]:
#To prevent above scnerio
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([ 1,  2, 30,  4,  5])

In [17]:
tensor_arr[2] =40
print(tensor_arr)
print(arr)

tensor([ 1,  2, 40,  4,  5])
[ 1  2 30  4  5]


In [18]:
##zeros and ones
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

##### Arithmetic Operation

In [20]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [21]:
torch.add(a,b)

tensor([ 7.,  9., 11.])